---
# source: https://github.com/djonasson/ansible-role-xdg_bds/blob/main/tasks/main.yml

- name: Include XDG vars
  ansible.builtin.include_vars: xdg_dir_vars.yml

- name: Ensure XDG_CACHE_HOME directory exists.
  ansible.builtin.file:
    mode: '0755'
    path: "{{ xdg_cache_home }}"
    state: directory

- name: Ensure XDG_CONFIG_HOME directory exists.
  ansible.builtin.file:
    mode: '0755'
    path: "{{ xdg_config_home }}"
    state: directory

- name: Ensure XDG_DATA_HOME directory exists.
  ansible.builtin.file:
    mode: '0755'
    path: "{{ xdg_data_home }}"
    state: directory

- name: Ensure XDG_STATE_HOME directory exists.
  ansible.builtin.file:
    mode: '0755'
    path: "{{ xdg_state_home }}"
    state: directory  

- name: Ensure XDG_BIN_HOME directory exists.
  ansible.builtin.file:
    mode: '0755'
    path: "{{ xdg_bin_home }}"
    state: directory  

