---
# - name: Restart services
#   ansible.builtin.systemd:
#     name: "{{ item }}"
#     state: restarted
#   loop: "{{ services.enable }}"

- name: Refresh font cache
  ansible.builtin.command: fc-cache -fv

- name: Update database for locate command
  ansible.builtin.command:
    cmd: updatedb

- name: Rebooting machine
  ansible.builtin.reboot:
  when: "ansible_connection != 'local'"

- name: Configure git-credential-manager
  ansible.builtin.command:
    cmd: git-credential-manager-core configure
