---
- name: "Install dev apt packages: {{ apt.install | join(', ') }}"
  ansible.builtin.apt:
    name: "{{ apt.install }}"
    state: latest
    update_cache: true
  tags:
    - apt
    - update
    - dev

- name: "Install python dev packages: {{ pip.install | join(', ') }}"
  become_user: "{{ user }}"
  ansible.builtin.pip:
    name: "{{ pip.install }}"
    state: latest
  tags:
    - pip
    - update
    - dev
