---
- name: Debug full machine facts
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Print connection type
      ansible.builtin.debug:
        var: ansible_connection